tecla = input('Digite algo: ')
print('Tipo ', type(tecla))
print('É numérica', tecla.isnumeric())
print('É alpha', tecla.isalpha())
print('É alphanumérica', tecla.isalnum())
print('É toda maíuscula', tecla.isupper())
print('É toda minúscula', tecla.islower())
print('É decimal', tecla.isdecimal())
print('É Somente espaço',tecla.isspace())
